# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    runs-on: macos-latest
    defaults: 
      run:
        working-directory: MyLibrary

    steps:
    - uses: actions/checkout@v3
    - name: Setup mock server
      run: |
        git clone https://github.com/ruangroc/cs561-mock-server.git
        pip install -r requirements.txt
        flask run &
    - name: Run tests
      run: swift test -v
